name = "actiontomltest"
defaultTargets = ["actiontomltest"]

[[lean_lib]]
name = "UseLeanActionWithTomlLakeFile"

[[lean_exe]]
name = "actiontomltest"
root = "Main"


[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"